server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/andylke/demo-spring-cloud-config-store.git
          default-label: main
          cloneOnStart: true
